# Generated by Django 3.0.7 on 2020-06-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField()),
                ('orderNumber', models.CharField(max_length=100)),
                ('customerID', models.CharField(max_length=100)),
                ('customerDesc', models.CharField(max_length=250)),
                ('pressDesc', models.CharField(max_length=250)),
                ('currency', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('NTamount', models.FloatField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
