# Generated by Django 3.0.7 on 2020-06-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='orderDate',
            field=models.DateField(),
        ),
    ]
