# Generated by Django 3.0.7 on 2020-06-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20200615_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='displayBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='display/images/')),
            ],
        ),
    ]
