# Generated by Django 3.0.7 on 2020-06-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_displaybackground'),
    ]

    operations = [
        migrations.CreateModel(
            name='custID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerID', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=250)),
                ('customerDesc', models.CharField(max_length=250)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
    ]
