# Generated by Django 3.0.7 on 2020-06-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_custid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custid',
            old_name='userName',
            new_name='username',
        ),
    ]
