# Generated by Django 3.0.7 on 2020-07-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20200622_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='custid',
            name='group',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
