# Generated by Django 3.0.7 on 2020-07-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_custid_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custid',
            name='group',
            field=models.CharField(max_length=250),
        ),
    ]
