# Generated by Django 3.0.7 on 2020-07-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_auto_20200728_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='group',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
