# Generated by Django 3.0.7 on 2020-07-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_purchase_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='group',
            field=models.CharField(max_length=250),
        ),
    ]
