# Generated by Django 3.0.7 on 2020-07-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_auto_20200729_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='orderDate',
            field=models.DateField(verbose_name='%m/%d/%Y'),
        ),
    ]
