# Generated by Django 3.0.7 on 2020-07-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0011_auto_20200729_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='custid',
            name='level',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
