# Generated by Django 3.0.7 on 2020-07-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0012_custid_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custid',
            name='level',
            field=models.CharField(max_length=250),
        ),
    ]
