# Generated by Django 3.0.7 on 2020-08-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0013_auto_20200729_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='NTamount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='country',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='pressDesc',
        ),
        migrations.AddField(
            model_name='purchase',
            name='orderDesc',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
