# Generated by Django 3.0.7 on 2020-08-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0014_auto_20200805_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='username',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
