# Generated by Django 3.0.7 on 2020-09-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0016_auto_20200829_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custid',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='orderDesc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='orderNumber',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
